-- ============================================
-- PULSE - Initial Database Schema
-- ============================================

-- Users
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Stock master
CREATE TABLE stock_master (
    symbol VARCHAR(20) PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    sector VARCHAR(100),
    exchange VARCHAR(20),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Watchlists
CREATE TABLE watchlists (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Stocks inside watchlists
CREATE TABLE watchlist_stocks (
    id BIGSERIAL PRIMARY KEY,
    watchlist_id BIGINT NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE,
    symbol VARCHAR(20) NOT NULL REFERENCES stock_master(symbol),
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_watchlist_stock UNIQUE (watchlist_id, symbol)
);

-- Market observations
CREATE TABLE market_snapshots (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL REFERENCES stock_master(symbol),
    price NUMERIC(18, 4) NOT NULL,
    volume BIGINT,
    timestamp TIMESTAMPTZ NOT NULL,
    source VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Detected market events
CREATE TABLE market_events (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL REFERENCES stock_master(symbol),
    event_type VARCHAR(50) NOT NULL,
    title VARCHAR(255),
    description TEXT,
    event_time TIMESTAMPTZ NOT NULL,
    source VARCHAR(100),
    source_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Signals generated by intelligence engine
CREATE TABLE market_signals (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL REFERENCES stock_master(symbol),
    signal_type VARCHAR(50) NOT NULL,
    value NUMERIC(18, 6),
    score NUMERIC(5, 2),
    metadata JSONB,
    timestamp TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User-facing attention events
CREATE TABLE attention_events (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    symbol VARCHAR(20) NOT NULL REFERENCES stock_master(symbol),
    event_id BIGINT REFERENCES market_events(id),

    attention_score NUMERIC(5, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DETECTED',

    first_detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    surfaced_at TIMESTAMPTZ,
    viewed_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User checkpoints
CREATE TABLE user_checkpoints (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    last_checked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User attention preferences
CREATE TABLE user_preferences (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),

    price_weight NUMERIC(5, 2) NOT NULL DEFAULT 30,
    relative_weight NUMERIC(5, 2) NOT NULL DEFAULT 25,
    event_weight NUMERIC(5, 2) NOT NULL DEFAULT 20,
    volume_weight NUMERIC(5, 2) NOT NULL DEFAULT 15,
    persistence_weight NUMERIC(5, 2) NOT NULL DEFAULT 10,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- Indexes
-- ============================================

CREATE INDEX idx_watchlists_user
    ON watchlists(user_id);

CREATE INDEX idx_watchlist_stocks_watchlist
    ON watchlist_stocks(watchlist_id);

CREATE INDEX idx_market_snapshots_symbol_timestamp
    ON market_snapshots(symbol, timestamp DESC);

CREATE INDEX idx_market_events_symbol_timestamp
    ON market_events(symbol, event_time DESC);

CREATE INDEX idx_market_signals_symbol_timestamp
    ON market_signals(symbol, timestamp DESC);

CREATE INDEX idx_attention_user_status_score
    ON attention_events(user_id, status, attention_score DESC);